
exports.up = function (knex) {
  return knex.raw (`
  CREATE TABLE IF NOT EXISTS lookup
  (
    id          int GENERATED BY DEFAULT AS IDENTITY,
    type        varchar(100) not null,
    key         varchar(200) not null,
    value       varchar(200) not null,
    sort_order  int          not null,
    is_active   boolean      not null default true,
    created_by  varchar(20)  not null,
    created_on  timestamptz  not null default now(),
    updated_by  varchar(20)  not null,
    updated_on  timestamptz  not null default now(),
    constraint lookup_pk primary key (id)
  );
  `)
};

exports.down = function(knex) {
  return knex.schema.dropTable('lookup');
};
